security:
    resource: "@AppSecurityBundle/Controller/"
    type: annotation
    prefix: %prefix_path%

fosuser_security:
    resource: "@AppSecurityBundle/Resources/config/routing.yml"
    prefix: %prefix_path%

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: %prefix_path%
