security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^%prefix_path%/(_(profiler|wdt)|css|images|js)/
            security: false
        login_firewall:
            pattern:    ^%prefix_path%fos_user_security_login$
            anonymous:  ~
        secured_area:
            pattern:    ^/
            anonymous:  ~
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: homepage
            logout:
                path:   fos_user_security_logout
                target: homepage

    access_control:
        - { path: ^%prefix_path%/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^%prefix_path%/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^%prefix_path%/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^%prefix_path%/, roles: [ 'ROLE_USER' ]}